# Generated by Django 4.2.28 on 2026-09-10 11:56
#
# This is a hand-authored data migration built on the makemigrations-generated skeleton
# above. See the docstring on gcp_to_edx_language_codes() below for what it does and why.
#
# Backfills VideoTranscript.language_code from GCP format to edX format for transcripts
# produced by ai-translations (provider="edx_ai_translations").
#
# Prior to https://github.com/edx/ai-translations/pull/475 (LP-1118), ai-translations converted
# edX language codes to GCP codes before calling update_val_transcript(), so this column ended up
# holding GCP codes (e.g. "es", "pt-BR") instead of the canonical edX codes (e.g. "es-419",
# "pt-br") used everywhere else on the platform. ai-translations now sends edX codes for new
# transcripts; this migration corrects the historical rows so old and new data are consistent.
#
# "es" is ambiguous -- both "es-419" and "es-es" collapse to "es" on the GCP side, and there is no
# way to recover which one a given row originally was. Per product decision, ambiguous "es" rows
# are assumed to have been "es-419". All other renames below are unambiguous 1:1 mappings.
#
# Only rows written by ai-translations (provider="edx_ai_translations") are touched. Transcripts
# from other providers (Custom, 3PlayMedia, Cielo24) were never subject to the GCP mapping and
# must not be reinterpreted by this migration.
#
# Because ai-translations has already been sending edX codes since LP-1118 shipped, a video may
# already have a row at the target edX code (e.g. a fresh "es-419" translation) by the time this
# migration runs against its older "es" row. VideoTranscript enforces
# unique_together = ("video", "language_code"), so in that case the stale GCP-coded row is dropped
# in favor of the row that is already correct, rather than renamed into a collision.

from django.db import migrations

PROVIDER_EDX_AI_TRANSLATIONS = "edx_ai_translations"

# Unambiguous 1:1 renames between GCP format and edX format.
GCP_TO_EDX_UNAMBIGUOUS = {
    "de": "de-de",
    "fr-CA": "fr-ca",
    "it": "it-it",
    "ko": "ko-kr",
    "pt-BR": "pt-br",
    "pt-PT": "pt-pt",
    "tr": "tr-tr",
    "zh-CN": "zh-cn",
}

# Ambiguous GCP code -> assumed edX code (product decision: assume "es-419", not "es-es").
GCP_TO_EDX_AMBIGUOUS = {
    "es": "es-419",
}

GCP_TO_EDX = {**GCP_TO_EDX_UNAMBIGUOUS, **GCP_TO_EDX_AMBIGUOUS}
EDX_TO_GCP = {edx_code: gcp_code for gcp_code, edx_code in GCP_TO_EDX.items()}


def _rename_language_code(VideoTranscript, db_alias, old_code, new_code):
    """
    Renames all edx_ai_translations VideoTranscript rows from old_code to new_code, dropping
    any old_code row that would otherwise collide with an existing new_code row for the same
    video (unique_together = ("video", "language_code")).
    """
    old_rows = VideoTranscript.objects.using(db_alias).filter(
        provider=PROVIDER_EDX_AI_TRANSLATIONS,
        language_code=old_code,
    )
    old_video_ids = set(old_rows.values_list("video_id", flat=True))
    if not old_video_ids:
        return

    colliding_video_ids = set(
        VideoTranscript.objects.using(db_alias)
        .filter(language_code=new_code, video_id__in=old_video_ids)
        .values_list("video_id", flat=True)
    )

    if colliding_video_ids:
        # A row for the target code already exists (e.g. a fresh translation created after
        # LP-1118 shipped) -- drop the stale GCP-coded duplicate rather than renaming into it.
        VideoTranscript.objects.using(db_alias).filter(
            provider=PROVIDER_EDX_AI_TRANSLATIONS,
            language_code=old_code,
            video_id__in=colliding_video_ids,
        ).delete()

    non_colliding_video_ids = old_video_ids - colliding_video_ids
    if non_colliding_video_ids:
        VideoTranscript.objects.using(db_alias).filter(
            provider=PROVIDER_EDX_AI_TRANSLATIONS,
            language_code=old_code,
            video_id__in=non_colliding_video_ids,
        ).update(language_code=new_code)


def gcp_to_edx_language_codes(apps, schema_editor):
    VideoTranscript = apps.get_model("edxval", "VideoTranscript")
    db_alias = schema_editor.connection.alias

    for gcp_code, edx_code in GCP_TO_EDX.items():
        _rename_language_code(VideoTranscript, db_alias, gcp_code, edx_code)


def edx_to_gcp_language_codes(apps, schema_editor):
    """
    Best-effort reverse. Note this is lossy for the ambiguous "es" case: any "es-es" rows
    created by ai-translations after this migration ran (as opposed to "es-419") cannot be told
    apart from "es-419" once both are collapsed back to "es", so on reverse they are merged under
    "es" like the original ambiguous data was, per the same collision-drop rule as the forward
    migration.
    """
    VideoTranscript = apps.get_model("edxval", "VideoTranscript")
    db_alias = schema_editor.connection.alias

    for edx_code, gcp_code in EDX_TO_GCP.items():
        _rename_language_code(VideoTranscript, db_alias, edx_code, gcp_code)


class Migration(migrations.Migration):

    dependencies = [
        ('edxval', '0005_videoaudiodescription'),
    ]

    operations = [
        migrations.RunPython(gcp_to_edx_language_codes, reverse_code=edx_to_gcp_language_codes),
    ]
